### ISSUE TITLE
NoClassDefFoundError when running on server

### ISSUE THREAD

**Issue by cj3636** [JPANv2/EMCBaubles#2]
```
java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_251] {}
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_251] {}
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_251] {}
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:228) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:221) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:138) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:72) ~[eventbus-2.2.0-service.jar:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:72) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) ~[?:31.2] {re:classloading}
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_251] {}
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_251] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_251] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_251] {}
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_251] {}
        at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_251] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251] {}
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_251] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:104) ~[modlauncher-5.1.2.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
        ... 40 more
        Suppressed: java.lang.ClassNotFoundException
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:263) ~[modlauncher-5.1.2.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-5.1.2.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.2.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
                at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_251] {}
                at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_251] {}
                at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_251] {}
                at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_251] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:228) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.register(EventBus.java:221) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:138) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:72) ~[eventbus-2.2.0-service.jar:?] {}
                at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251] {}
                at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:72) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-2.2.0-service.jar:?] {}
                at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}
                at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_251] {}
                at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) ~[?:31.2] {re:classloading}
                at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_251] {}
                at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_251] {}
                at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
                at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?] {re:classloading}
                at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_251] {}
                at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_251] {}
                at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_251] {}
                at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_251] {}
                at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_251] {}
                at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251] {}
                at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251] {}

```

Appears the mpod is not performing a remote/client side check when calling the `net/minecraft/client/util/ITooltipFlag` class.

Issue is detrimental and will not run on server.

MC 1.15.2 
Forge 31.2.31
JJVM 1.8_251

**Comment by JPANv2** [comment]
I have zero experience with servers, so it was kinda hard to test this fully. So far, it appears fixed in forge server, but if there is anything else, please comment here.
